### ISSUE TITLE
I am very interested in your open-source dataset.

### ISSUE THREAD

**Issue by 865979216** [farhancv09/Vessel_Segmentation#2]
I saw that the TubeTK dataset only has 42 groundtruth cases, so did you only use 42 cases in Tube TK Labelled(TTKL)?

**Comment by 865979216** [comment]
Could you open source the remaining dataset(TTKU_L)? thank you！

**Comment by farhancv09** [comment]
Thank you for your interest. 

I am attaching the link for TTKU_L labels (55 patients) which is labeled by us. I couldn't able to find the original names of files but you can match the metadata of images with original images metadata (probably you can find some difference). And the images I have are preprocessed (skull stripped and vessel enhancement).

Disclaimer: The labels are not good as tubetk original labels as we aimed only major arteries. 
Link: https://drive.google.com/drive/folders/1fpUnzHK5_Csnrc3E6x2jgFHZEDm9aQGX?usp=drive_link

**Comment by 865979216** [comment]
Thank you for your reply. Thank you for your datase. I will consider using it at my discretion
